# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Reusable cross-platform workflow to setup for the build environment.
# * Install Python and required Python packages
# * Install Unity, platform build support, and register license if
#   username, password and serial id are provided
name: 'Build Setup'

inputs:
  unity_version:
    required: true
  platform:
    description: 'Platform to install Unity on (Windows,macOS,Linux)'
    type: choice
    options:
      - Windows
      - macOS
      - Linux
    required: true
  unity_username:
    required: false
  unity_password:
    required: false
  unity_serial_id:
    required: false
  python_version:
    required: true

runs:
  using: 'composite'
  steps:
    # Download GHA tools and requirements from Firebase Unity SDK repo
    - uses: actions/checkout@v3
      with:
        repository: firebase/firebase-unity-sdk
        path: external/firebase-unity-sdk
        sparse-checkout: |
          scripts/gha/requirements.txt
        sparse-checkout-cone-mode: false

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install python deps
      shell: bash
      run: |
        pip install -r ./external/firebase-unity-sdk/scripts/gha/requirements.txt

    - name: Install Unity and get a license
      uses: firebase/firebase-unity-sdk/gha/unity@main
      with:
        version: ${{ inputs.unity_version }}
        # iOS build support is always required to build EDM4U
        platforms: "${{ inputs.platform }},iOS,Android"
        username: ${{ inputs.unity_username }}
        password: ${{ inputs.unity_password }}
        serial_ids: ${{ inputs.unity_serial_id }}

