# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Workflow to build EDM4U packages and compute their hash
name: Build

on:
  schedule:
    - cron: "0 10 * * *"  # 10am UTC = 2am PST

  pull_request:
    types: [ labeled, closed ]

  workflow_dispatch:
    inputs:
      unity_version:
        description: 'Unity version'
        default: '2019'
        type: string
        required: true

env:
  # Use SHA256 for hashing files.
  hashCommand: "sha256sum"

jobs:
  check_and_prepare:
    runs-on: ubuntu-latest
    outputs:
      unity_version: ${{ steps.set_outputs.outputs.unity_version }}
    steps:
      - id: set_outputs
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "unity_version=${{ github.event.inputs.unity_version }}" >> $GITHUB_OUTPUT
          else
            # inputs are not available for non "workflow_dispatch" events. Therefore, set default value here.
            echo "unity_version=2019" >> $GITHUB_OUTPUT
          fi

      - name: Print output
        run: |
          echo outputs.unity_version : ${{ steps.set_outputs.outputs.unity_version }}

  build_macos:
    name: build-macos-unity${{ needs.check_and_prepare.outputs.unity_version }}
    needs: [check_and_prepare]
    uses: ./.github/workflows/build_macos.yaml
    with:
      unity_version: ${{ needs.check_and_prepare.outputs.unity_version }}

  finalizing:
    # Only compute SHA hash for macOS build
    name: finalizing-macOS-unity${{ needs.check_and_prepare.outputs.unity_version }}
    needs: [check_and_prepare, build_macos]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch All builds
        uses: actions/download-artifact@v3
        with:
          path: built_artifact

      - name: Compute Plugin Hash
        shell: bash
        run: |
          # Compute hash for .tgz package
          pushd built_artifact/TarballPackage_macOS
          tgz_files_list=$(find -type f -name '*.tgz')
          for tgz_file in "${tgz_files_list[@]}"; do
            echo tgz_file
            ${{ env.hashCommand }} --tag ${tgz_file} >> edm4u_hash.txt
          done
          echo "::warning ::$(cat edm4u_hash.txt)"
          popd

          # Compute hash for .unitypackage package
          pushd built_artifact/AssetPackage_macOS
          ${{ env.hashCommand }} --tag external-dependency-manager.unitypackage >> edm4u_hash.txt
          echo "::warning ::$(cat edm4u_hash.txt)"
          popd


